http:
 listener:
  host: "0.0.0.0"
  port: "8081"
  readTimeOut: "3000"
  
  
businessProcessName: "Student Registration"

db:
 host:"localhost"
 port:"3306"
 Database:"stu"
 userName:"root"
 password:"root"