#%RAML 1.0 Library
usage:
traits:
  common-headers: !include traits/common-header-trait.raml
  authorization-headers: !include traits/authorization-trait.raml
  header-headers: !include traits/header-trait.raml
  error-response: !include traits/error-response-trait.raml
 
types:
  request-record-stu: !include datatypes/record-stu-req-dataType.raml
  response-record-stu: !include datatypes/record-stu-res-dataType.raml  
  update-stu-req: !include datatypes/update-stu-req-dataType.raml
  update-stu-res: !include datatypes/update-stu-res-dataType.raml
  retreive-stu-res: !include datatypes/retreive-stu-dataType.raml
